// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/payment-flows/MultiPayment.tsx": () => import("../components/mockups/payment-flows/MultiPayment.tsx"),
  "./components/mockups/payment-flows/Overview.tsx": () => import("../components/mockups/payment-flows/Overview.tsx"),
  "./components/mockups/payment-flows/SplitBill.tsx": () => import("../components/mockups/payment-flows/SplitBill.tsx")
};
