import { Database } from '../../database';
import { BaseRepository } from '../BaseRepository';
import {
  paymentProviderEvents,
  type PaymentProviderEvent,
  type InsertPaymentProviderEvent,
} from '../../../../shared/schema';
import { and, eq } from 'drizzle-orm';

export interface IPaymentProviderEventRepository {
  /**
   * Insert a new provider event row.
   * Pass `tx` when called inside a db.transaction() to keep the operation atomic.
   */
  create(data: InsertPaymentProviderEvent, tx?: any): Promise<PaymentProviderEvent>;

  /**
   * Find an existing event by (provider, providerEventId).
   * The uniqueness is global — not scoped by tenant — because providerEventId is
   * generated by the external provider and is unique per provider.
   * Pass `tx` to read within an active transaction.
   */
  findByProviderEventId(
    provider: string,
    providerEventId: string,
    tx?: any,
  ): Promise<PaymentProviderEvent | null>;

  /**
   * Mark an event as successfully processed.
   * Sets processingStatus = 'processed' and processedAt = now().
   */
  markProcessed(id: string, data?: { processedAt?: Date }, tx?: any): Promise<PaymentProviderEvent>;

  /**
   * Mark an event as failed (e.g. transaction not found, DB error).
   * Sets processingStatus = 'failed' and errorMessage.
   */
  markFailed(id: string, errorMessage: string, tx?: any): Promise<PaymentProviderEvent>;

  /**
   * Mark an event as ignored (e.g. unsupported event type, TRANSACTION_ALREADY_TERMINAL).
   * Sets processingStatus = 'ignored' and errorMessage to the reason string.
   */
  markIgnored(id: string, reason: string, tx?: any): Promise<PaymentProviderEvent>;
}

export class PaymentProviderEventRepository
  extends BaseRepository<PaymentProviderEvent, InsertPaymentProviderEvent>
  implements IPaymentProviderEventRepository
{
  protected table = paymentProviderEvents;
  protected entityName = 'PaymentProviderEvent';

  constructor(db: Database) {
    super(db);
  }

  async create(data: InsertPaymentProviderEvent, tx?: any): Promise<PaymentProviderEvent> {
    try {
      const client = tx ?? this.db;
      const [result] = await client.insert(paymentProviderEvents).values(data).returning();
      return result;
    } catch (error) {
      this.handleError('create', error);
    }
  }

  async findByProviderEventId(
    provider: string,
    providerEventId: string,
    tx?: any,
  ): Promise<PaymentProviderEvent | null> {
    try {
      const client = tx ?? this.db;
      const rows = await client
        .select()
        .from(paymentProviderEvents)
        .where(
          and(
            eq(paymentProviderEvents.provider, provider),
            eq(paymentProviderEvents.providerEventId, providerEventId),
          ),
        )
        .limit(1);
      return rows[0] ?? null;
    } catch (error) {
      this.handleError('find by provider event id', error);
    }
  }

  async markProcessed(
    id: string,
    data?: { processedAt?: Date },
    tx?: any,
  ): Promise<PaymentProviderEvent> {
    try {
      const client = tx ?? this.db;
      const [result] = await client
        .update(paymentProviderEvents)
        .set({
          processingStatus: 'processed',
          processedAt: data?.processedAt ?? new Date(),
          errorMessage: null,
        })
        .where(eq(paymentProviderEvents.id, id))
        .returning();
      return result;
    } catch (error) {
      this.handleError('mark processed', error);
    }
  }

  async markFailed(id: string, errorMessage: string, tx?: any): Promise<PaymentProviderEvent> {
    try {
      const client = tx ?? this.db;
      const [result] = await client
        .update(paymentProviderEvents)
        .set({
          processingStatus: 'failed',
          errorMessage,
        })
        .where(eq(paymentProviderEvents.id, id))
        .returning();
      return result;
    } catch (error) {
      this.handleError('mark failed', error);
    }
  }

  async markIgnored(id: string, reason: string, tx?: any): Promise<PaymentProviderEvent> {
    try {
      const client = tx ?? this.db;
      const [result] = await client
        .update(paymentProviderEvents)
        .set({
          processingStatus: 'ignored',
          errorMessage: reason,
        })
        .where(eq(paymentProviderEvents.id, id))
        .returning();
      return result;
    } catch (error) {
      this.handleError('mark ignored', error);
    }
  }
}
